Task_Management/Task_App/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('index1/', views.index1, name='index1'),
    path('task/', views.task, name='task'),
    # path('search/', views.task, name='task'),
]

Task_Management/Task_Management/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('Task_App/', include('Task_App.urls')),
    path('admin/', admin.site.urls),
]

Task_Management/Task_App/models.py
from django.db import models
from django.forms import ModelForm


class Tasks(models.Model):
    Task_Name = models.CharField(max_length=64)
    Task_Description = models.CharField(max_length=256)
    Task_Type = models.CharField(
        max_length=256,
        choices=[
            ('MJ',"Major"),
            ('MN',"Minor"),
            ('PRJ',"Project")
        ]
    )
    Task_Grade = models.DecimalField(max_digits=5, decimal_places=2)
    Due_Date = models.DateTimeField()

class TaskForm(ModelForm):
    class Meta:
        model = Tasks
        fields = ['Task_Name', 'Task_Description', 'Task_Type', 'Task_Grade', 'Due_Date']

Task_Management/Task_App/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Tasks,TaskForm
from django.urls import reverse

def index1(request):
    task_apps = Tasks.objects.all() 
    context = {'task_apps': task_apps} 
    return render(request, 'web_design.html', context)

def task(request): 
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index1'))
    else:
        form = TaskForm()

    return render(request, 'task.html', {'form': form})

Task_Management/templates/base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        <p>something</p>
        {% endblock %}
    </title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"> 
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <style>
        p{
            background-image: url('../../website_home_bg.png');
            height: 100px;
            width: 100px;
        }
    </style>
</head>
<body bgcolor="Grey">
     <center><h1 style="color:blue;">Assignment View Homepage</h1></center>
    {% block content %}
    {% endblock %}
    <p>

    </p>
</body>
</html>

Task_Management/templates/extend.html
{% extends 'base.html' %}

{% block title %}Welcome!{% endblock %}

{% block content %}
<p>Welcome to Task Management Portal</p>
{% endblock %}

Task_Management/templates/task.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Task Item{% endblock %}

{% block content %}
<!-- <img src="{% static 'example_app/brownie.png' %}" alt="brownie"> -->
<center><img src="{% static 'Task_App/webpic.png' %}" alt="webpic" height="500" width="1430"></center>
<p><center><h2>Please use the following form to create the Assignment</h2></center></p>
<form action="{% url 'task' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<script> 
    flatpickr("#id_Due_Date", {enableTime: true, dateFormat: "Y-m-d H:i"}); 
</script>
{% endblock %}

Task_Management/templates/web_design.html
{% extends 'base.html' %}

{% block title %}Task Management{% endblock %}


{% block content %}
<h2 style="color: rgb(229, 255, 0);">Assignment Details</h2>
<ul>
{% for task_app in task_apps %}
    <li><h5 style="color: rgb(143, 14, 14);">{{ task_app.Task_Name }}</h5></li>
    <hr style="width:50%;text-align:left;margin-left:0"> 
    <li>{{ task_app.Task_Description }}</li>
    <li>{{ task_app.Task_Type }}</li>
    <li>{{ task_app.Task_Grade }}</li>
    <li>{{ task_app.Due_Date }}</li>
    <br>
{% endfor %}
</ul>
{% endblock %}